[package]
name = "hilbertplot"
version = "0.1.0"
edition = "2021"
authors = ["Darío Fragas <dariofg98@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
